defaults:
        - scanner: Bruker_PET_MRI_scanner_Validado_modif_WE20 

simulation_environment: 1
sim_type: "SimSET"
do_simulation: 1       
do_reconstruction: 0 
divisions: 10
model_type: "cylindrical"                
patient_dirname: "NEMA_NECR_Phantoms_preclinical"
act_map: "NECR_claudia_26_act.hdr"                 
att_map: "NECR_claudia_26_att.hdr" 
output_dir: "Prueba_NECR_1.080mCi_1seg_WE20_WC5"
center_slice: 70        
total_dose:  1.080
simulation_time: 1      #600
sampling_photons: 0   #20000000
photons: 0
add_randoms: 1  #modificado para NEC debe ser 1
phglistmode: 0
detlistmode: 0
recons_type: 0
maximumIteration: 1
