scanner_name: "Bruker_PET_MRI_scanner_Validado_modif_WE20"
simset_material: 29 
average_doi: 0.84
scanner_radius: 5.25                         
num_rings: 100                                                  
axial_fov: 15
z_crystal_size: 0.1497                                   
transaxial_crystal_size: 0.241             
crystal_thickness: 1 
energy_resolution: 17 
num_aa_bins: 68                       
num_td_bins: 136     
min_energy_window: 409    #ventana a un 20% del pico 
max_energy_window: 613 
coincidence_window: 5    #5 valor original 
numberOfSubsets: 1 
numberOfIterations: 48   
savingInterval: 16
analytical_att_correction: 0
stir_recons_att_corr: 0  # cambiarlo a 1
analytic_scatt_corr_factor: 0 # modif de 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D"
inter_iteration_filter: 1 # 0 no se está filtrando
subiteration_interval: 48
x_dir_filter_FWHM: 0.7
y_dir_filter_FWHM: 1 
z_dir_filter_FWHM: 0 
psf_value: 0                       #Hace una convolución con psf para cuantificar la incertidumbre de efectos que no simulamos (efectos dentro del cristal). La ponemos a 0 para estudiar sin esta corrección.
add_noise: 0                       #Como en el anterior filtrado se elimina el ruido, añadimos este analíticamente.
max_segment: 30 #99                         
zoomFactor: 1.0294                   # 0.795 para pixel de 0.75mm
xyOutputSize: 120                  
zOutputSize:  200   #200                  
zOutputVoxelSize: 3.27           

# NOTAS

# El pixel en z corresponde a la mitad del tamaño del cristal.
# El pixel en x,y viene asociado al zoom factor.

# bin_size=2*scanner_radius/num_td_bins
# xyVoxelsize=10*bin_size/zoom
# zVoxelsize=z_crystal_size/2
