scanner_name: "GE Advance"
simset_material: 10
average_doi: 0.0
scanner_radius: 46.35
num_rings: 18
axial_fov: 15.2
z_crystal_size: 0.81
transaxial_crystal_size: 0.4
crystal_thickness: 3
energy_resolution: 20
num_aa_bins: 336
num_td_bins: 281
min_energy_window: 375
max_energy_window: 675
coincidence_window: 12.5
numberOfSubsets: 14
numberOfIterations: 56
savingInterval: 28
analytical_att_correction: 1
stir_recons_att_corr: 0
analytic_scatt_corr_factor: 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D"
inter_iteration_filter: 0
subiteration_interval:
x_dir_filter_FWHM:
y_dir_filter_FWHM:
z_dir_filter_FWHM:
psf_value: 1.125
add_noise: 0.01
max_segment: 11
zoomFactor: 1.69
xyOutputSize: 128
zOutputSize: 35
zOutputVoxelSize: 4.25
