scanner_name: "GE Advance"
validation_status: "None"     # None, Partial, Validated

# Scanner Description
# --------------------------------------
simset_material: 10           # BGO
average_doi: 0.0              # cm
scanner_radius: 46.35         # Scanner radius
num_rings:  18                # Number of rings
axial_fov: 15.2               # Axial FOV max (cm) 
transaxial_fov: 84            # Transaxial FOV (If unknown use diameter) 
crystals_per_ring: 672        # Number of crystals per ring ¿Unused?

# Crystal Description
#----------------------------------------
transaxial_crystal_size: 0.4 # Transaxial Crystal size (cm).
z_crystal_size: 0.81          # Axial Crystal size (cm)
crystal_thickness: 3          # Crystal Thickness (cm)

# Energy characteristics
#-----------------------------------------
energy_resolution: 20          # Energy resolution (%)
min_energy_window:  375
max_energy_window:  675

# Sinogram creation
#-----------------------------------------
# Binning
num_aa_bins:  336            # Number of views (Numero de detectores por anillo divido por 2)
num_td_bins:  281            # Number of bins

# Coincidence window (ns)
coincidence_window: 12.5     # nanoseconds. Used only for random simulation (SimSET)

# Sinogram pre-processing
psf_value: 1.125
add_noise: 0.01

# Corrections
#-----------------------------------
# Attenuation correction
analytical_att_correction: 1    # Performed by SimSET calcattenuation
stir_recons_att_corr: 0         # Performed in STIR by entering the att image as a normalization map

# Scatter Correction
analytic_scatt_corr_factor:  0.15   # 0.15 WILL REMOVE 85% of scatter.0 will remove scatter
stir_scatt_corr_smoothing:   0      # Will use smoothed SimSET scatter as additive_sinogram.

# Randoms Correction
analytic_randoms_corr_factor: 0.2    # 0.15 WILL REMOVE 85% of scatter.0 will remove randoms
stir_randoms_corr_smoothing: 0       # Will include smoothed SimSET randoms in the additive_sinogram.

# Reconstruction
#-----------------------------------
recons_type: "OSEM3D"
max_segment: 11              # Maximum Ring difference on the reconstruction

# Configure Reconstruction output
zoomFactor: 1.69             # Zoom factor in x and y
xyOutputSize: 128
zOutputSize: 35
xyOutputVoxelSize: 2         # mm
zOutputVoxelSize: 4.25       # mm
numberOfSubsets: 14          # Number of subsets
numberOfIterations: 56       # Number of iterations
savingInterval: 28           # The interval that we want to save intermediate subiterations images

# Filter
inter_iteration_filter: 0 #1 for activate, 0 for deactivate
subiteration_interval: 
x_dir_filter_FWHM:  # in mm
y_dir_filter_FWHM:  # in mm
z_dir_filter_FWHM:  # in mm