scanner_name: "Inveon"
validation_status: "None"       # None, Partial, Validated

# Scanner Description
#---------------------------------------------------------------------------------------------------
simset_material: 18           # LSO
average_doi: 0.26             # 23.3 mm (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7239556/)
scanner_radius: 8.5           # Scanner radius (cm)
num_rings:  80                # Number of rings
axial_fov: 12.7               # Axial FOV max (cm)
transaxial_fov: 10.0         # If unknown the scanner diameter should be set
crystals_per_ring: 320        # Number of crystals per ring

# Crystal description
#----------------------------------------------------------------------------------------------------
transaxial_crystal_size: 0.151 # Transaxial Crystal size (cm).
z_crystal_size: 0.151           # Axial Crystal size (cm)
crystal_thickness: 1          # Crystal Thickness (cm)

#Energy characteristics
#----------------------------------------------------------------------------------------------------
energy_resolution: 16          # Energy resolution (%)
min_energy_window:  350
max_energy_window:  650

# Sinogram creation
#----------------------------------------------------------------------------------------------------
# Binning
num_aa_bins:  160            # Number of views (Numero de detectores por anillo divido por 2)
num_td_bins:  100          # Number of bins

# Coincidence window (ns)
coincidence_window: 3.43        # nanoseconds. Used only for random simulation (SimSET)

# Sinogram pre-processing
psf_value: 0
add_noise: 0

#Corrections
#----------------------------------------------------------------------------------------------------
# Attenuation correction
analytical_att_correction: 1    # Performed by SimSET calcattenuation
stir_recons_att_corr: 0        # Performed in STIR by entering the att image as a normalization map

# Scatter Correction
analytic_scatt_corr_factor:  0.3      # 0.15 WILL REMOVE 85% of scatter.0 will remove scatter
stir_scatt_corr_smoothing:   0      # Will use smoothed SimSET scatter as additive_sinogram.

# Randoms Correction
analytic_randoms_corr_factor: 0.3     # 0.15 WILL REMOVE 85% of scatter.0 will remove randoms
stir_randoms_corr_smoothing: 0       # Will include smoothed SimSET randoms in the additive_sinogram.

# Reconstruction
#----------------------------------------------------------------------------------------------------
recons_type: "OSEM3D"
max_segment: 79             # Maximum Ring difference on the reconstruction

#Configure Reconstruction output
zoomFactor: 2              # Zoom factor in x and y
xyOutputSize: 256
zOutputSize: 159
xyOutputVoxelSize: 0.8
zOutputVoxelSize: 0.8          # mm
numberOfSubsets: 10          # Number of subsets
numberOfIterations: 100      # Number of iterations
savingInterval: 20           # The interval that we want to save intermediate subiterations images

# Filter
inter_iteration_filter: 1 #1 for activate, 0 for deactivate
subiteration_interval: 10
x_dir_filter_FWHM: 1 # in mm
y_dir_filter_FWHM: 1 # in mm
z_dir_filter_FWHM: 1@ # in mm



