scanner_name: "Albira_SI"
validation_status: "None"       # None, Partial, Validated

# Scanner Description
#--------------------------------------------
simset_material: 29           # LYSO
average_doi: 0.23             # 23.3 mm (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7239556/)
scanner_radius: 4         # Scanner radius
num_rings:  36                # Number of rings
axial_fov: 14.8               # Axial FOV max (cm)
transaxial_fov: 8
crystals_per_ring: 

# Crystal Description
#---------------------------------------------
transaxial_crystal_size: 0.42 # Transaxial Crystal size (cm).
z_crystal_size: 0.42           # Axial Crystal size (cm)
crystal_thickness: 1          # Crystal Thickness (cm)

# Energy characteristics
#---------------------------------------------
energy_resolution: 16          # Energy resolution (%)
min_energy_window:  425
max_energy_window:  600

#Sinogram creation
#----------------------------------------------
# Binning
num_aa_bins:  48            # Number of views (Numero de detectores por anillo divido por 2)
num_td_bins:  18            # Number of bins

#Coincidence window (ns)
coincidence_window: 2        # nanoseconds. Used only for random simulation (SimSET)

# Sinogram pre-processing
psf_value: 0
add_noise: 0

# Corrections
#--------------------------------------------------
# Attenuation Correction
analytical_att_correction: 1    # Performed by SimSET calcattenuation
stir_recons_att_corr: 0        # Performed in STIR by entering the att image as a normalization map

# Scatter Correction
analytic_scatt_corr_factor:  0.3      # 0.15 WILL REMOVE 85% of scatter.0 will remove scatter
stir_scatt_corr_smoothing:   0      # Will use smoothed SimSET scatter as additive_sinogram.

 # Randoms Correction
analytic_randoms_corr_factor: 0.3     # 0.15 WILL REMOVE 85% of scatter.0 will remove randoms
stir_randoms_corr_smoothing: 0       # Will include smoothed SimSET randoms in the additive_sinogram.

# Reconstruction
#---------------------------------------------------
recons_type: "OSEM3D"
max_segment: 35          # Maximum Ring difference on the reconstruction

# Configure reconstruction output
zoomFactor: 1            # Zoom factor in x and y
xyOutputSize: 128
zOutputSize: 71
xyOutputVoxelSize: 0.8      # mm
zOutputVoxelSize: 1         # mm
numberOfSubsets: 6          # Number of subsets
numberOfIterations: 32      # Number of iterations
savingInterval: 8           # The interval that we want to save intermediate subiterations images

# Filter
inter_iteration_filter: 0 #1 for activate, 0 for deactivate
subiteration_interval: 4
x_dir_filter_FWHM: 0.5 # in mm
y_dir_filter_FWHM: 0.5 # in mm
z_dir_filter_FWHM: 0.5 # in mm



