scanner_name: RandomScanner 0
simset_material: '29'
average_doi: 0.1
coincidence_window: 3.9
scanner_radius: 44.31
axial_fov: 17.316
z_crystal_size: 0.778
transaxial_crystal_size: 0.63
crystal_thickness: 1.910
num_rings: 22
energy_resolution: 10.827
min_energy_window: 460.410
max_energy_window: 551.407
num_aa_bins: 210
num_td_bins: 135
numberOfSubsets: 7
numberOfIterations: 10
max_segment: 19
zOutputSize: 43
xyOutputSize: 128
zoomFactor: 1.5
zOutputVoxelSize: 3.27
savingInterval: 3
recons_type: OSEM3D
psf_value: 0
subiteration_interval: 0
x_dir_filter_FWHM: 0
y_dir_filter_FWHM: 0
z_dir_filter_FWHM: 0
analytical_att_correction: 1
stir_recons_att_corr: 0
stir_randoms_corr_smoothing: 0
stir_scatt_corr_smoothing: 0
analytic_scatt_corr_factor: 0.25
analytic_randoms_corr_factor: 0.4
inter_iteration_filter: 0
stir_scatt_simulation: 0
add_noise: 0
