scanner_name: Scanner 0
simset_material: '10'
average_doi: 0.1
coincidence_window: 11.35
scanner_radius: 34.612
axial_fov: 18.227
z_crystal_size: 0.517
transaxial_crystal_size: 0.506
crystal_thickness: 2.885
num_rings: 33
energy_resolution: 14.567
min_energy_window: 447.783
max_energy_window: 574.217
num_aa_bins: 215
num_td_bins: 116
numberOfSubsets: 5
numberOfIterations: 25
max_segment: 26
zOutputSize: 65
xyOutputSize: 512
zoomFactor: 11.336
add_noise: 0
stir_scatt_simulation: 0
savingInterval: 25
recons_type: OSEM3D
psf_value: 0
subiteration_interval: 0
x_dir_filter_FWHM: 0
y_dir_filter_FWHM: 0
z_dir_filter_FWHM: 0
analytical_att_correction: 1
stir_recons_att_corr: 0
stir_randoms_corr_smoothing: 0
stir_scatt_corr_smoothing: 0
inter_iteration_filter: 0
analytic_scatt_corr_factor: 0.25
analytic_randoms_corr_factor: 0.45
