scanner_name: Scanner 10
simset_material: '10'
average_doi: 1.05
coincidence_window: 11.35
scanner_radius: 33.8
axial_fov: 18.1
z_crystal_size: 0.5
transaxial_crystal_size: 0.6
crystal_thickness: 2.5
num_rings: 39
energy_resolution: 11.9
min_energy_window: 452.2
max_energy_window: 568.2
num_aa_bins: 178
num_td_bins: 99
numberOfSubsets: 2
numberOfIterations: 18
max_segment: 35
zOutputSize: 77
zOutputVoxelSize: 3.27
xyOutputSize: 448
zoomFactor: 1.5
savingInterval: 18
recons_type: OSEM3D
psf_value: 0
subiteration_interval: 0
x_dir_filter_FWHM: 0
y_dir_filter_FWHM: 0
z_dir_filter_FWHM: 0
analytical_att_correction: 1
stir_recons_att_corr: 0
stir_randoms_corr_smoothing: 0
stir_scatt_corr_smoothing: 0
analytic_scatt_corr_factor: 0.3
analytic_randoms_corr_factor: 0.4
