scanner_name: Scanner 11
simset_material: '18'
average_doi: 1.16
coincidence_window: 4.94
scanner_radius: 36.353
axial_fov: 21.36
z_crystal_size: 0.691
transaxial_crystal_size: 0.461
crystal_thickness: 1.978
num_rings: 30
energy_resolution: 16.704
min_energy_window: 438.511
max_energy_window: 583.489
num_aa_bins: 248
num_td_bins: 129
numberOfSubsets: 8
numberOfIterations: 40
max_segment: 22
zOutputSize: 59
xyOutputSize: 320
zoomFactor: 2.456
add_noise: 0
stir_scatt_simulation: 0
savingInterval: 40
recons_type: OSEM3D
psf_value: 0
subiteration_interval: 0
x_dir_filter_FWHM: 0
y_dir_filter_FWHM: 0
z_dir_filter_FWHM: 0
analytical_att_correction: 1
stir_recons_att_corr: 0
stir_randoms_corr_smoothing: 0
stir_scatt_corr_smoothing: 0
inter_iteration_filter: 0
analytic_scatt_corr_factor: 0.45
analytic_randoms_corr_factor: 0.3
