scanner_name: "Siemens Biograph mCT"
simset_material: 18
average_doi: 0.1
scanner_radius: 42.1
num_rings: 52
axial_fov: 21.8
z_crystal_size: 0.4
transaxial_crystal_size: 0.4
crystal_thickness: 2
energy_resolution: 11.5
num_aa_bins: 312
num_td_bins: 312
min_energy_window: 435
max_energy_window: 650
coincidence_window: 4.1
numberOfSubsets: 26
numberOfIterations: 130
savingInterval: 26
analytical_att_correction: 0
stir_recons_att_corr: 1
analytic_scatt_corr_factor: 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D"
inter_iteration_filter: 0
subiteration_interval: 4
x_dir_filter_FWHM:
y_dir_filter_FWHM:
z_dir_filter_FWHM:
psf_value: 1
add_noise: 0
max_segment: 49
zoomFactor: 2.65
xyOutputSize: 400
zOutputSize: 148
zOutputVoxelSize: 1.50

