scanner_name: "Siemens Biograph mMR"
validation_status: "None"     # None, Partial, Validated

# Scanner Description
#-------------------------------------
simset_material: 18        # LSO
average_doi: 0.7           # cm
scanner_radius: 32.8       # Scanner radius
num_rings: 64              # Number of rings
axial_fov: 25.8            # Axial FOV max (cm)
transaxial_fov: 64.0       # Transaxial FOV (If unknown use diameter) 
crystals_per_ring: 448     # Number of crystals per ring ¿Unused?

# Crystal Description
#--------------------------------------
transaxial_crystal_size: 0.4 # Transaxial Crystal size (cm)
z_crystal_size: 0.4
crystal_thickness: 2         # Crystal Thickness (cm)

# Energy characteristics
#---------------------------------------
energy_resolution: 14.5      # Energy resolution (%)
min_energy_window:  430
max_energy_window:  610

# Sinogram creation
#----------------------------------------
# Binning
num_aa_bins:  224         # Number of views (Numero de detectores por anillo divido por 2)
num_td_bins:  292         # Number of bins

# Coincidence window (ns)
coincidence_window: 5.86  # nanoseconds. Used only for random simulation (SimSET)

# Sinogram pre-processing
psf_value: 1 #1.125
add_noise: 0

# Corrections
#------------------------------------
# Attenuation correction
analytical_att_correction: 0    # Performed by SimSET calcattenuation
stir_recons_att_corr: 1        # Performed in STIR by entering the att image as a normalization map

# Scatter Correction
analytic_scatt_corr_factor:  0.15      # 0.15 WILL REMOVE 85% of scatter.0 will remove scatter
stir_scatt_corr_smoothing:   0      # Will use smoothed SimSET scatter as additive_sinogram.

# Randoms Correction
analytic_randoms_corr_factor: 0.2     # 0.15 WILL REMOVE 85% of scatter.0 will remove randoms
stir_randoms_corr_smoothing: 0       # Will include smoothed SimSET randoms in the additive_sinogram.

# Reconstruction
#-------------------------------------
recons_type: "OSEM3D"
max_segment:  60         # Maximum Ring difference on the reconstruction

# Configure Reconstruction output
zoomFactor: 1.07 #0.91   # Zoom factor in x and y
xyOutputSize:  344     
zOutputSize:  127
xyOutputVoxelSize: 2.0   # mm
zOutputVoxelSize: 2.0    # mm  
numberOfSubsets:  28     # Number of subsets
numberOfIterations: 112  # Number of iterations
savingInterval: 28       # The interval that we want to save intermediate subiterations images

# Filter
inter_iteration_filter: 0 #1 for activate, 0 for deactivate
subiteration_interval: 4
x_dir_filter_FWHM:  # in mm
y_dir_filter_FWHM:  # in mm
z_dir_filter_FWHM:  # in mm