scanner_name: "Philips Vereos"
validation_status: "None"     # None, Partial, Validated

# Scanner Description
#--------------------------------
simset_material: 29          # LYSO
average_doi: 1.1             # cm
scanner_radius: 38.2         # Scanner radius
num_rings: 40                # Number of rings
axial_fov: 16.4              # Axial FOV max (cm)
transaxial_fov: 76.4         # cm
crystals_per_ring: 612       # Number of crystals per ring ¿Unused?

# Crystal Description
#---------------------------------
transaxial_crystal_size: 0.4 # Transaxial Crystal size (cm)
z_crystal_size: 0.4          # Axial Crystal size (cm)
crystal_thickness: 1.9       # Crystal Thickness (cm)

# Energy characteristics
#-----------------------------------
energy_resolution: 11.3      # Energy resolution (%)
min_energy_window: 450
max_energy_window: 613

# Sinogram creation
#------------------------------------
# Binning
num_aa_bins: 306             # Number of views (Numero de detectores por anillo divido por 2)
num_td_bins: 306             # Number of bins

# Coincidence window (ns)
coincidence_window: 4        # nanoseconds. Used only for random simulation (SimSET)

# Sinogram pre-processing
psf_value: 0
add_noise: 0

# Corrections
#-------------------------------------
# Attenuation correction
analytical_att_correction: 1    # Performed by SimSET calcattenuation
stir_recons_att_corr:  0        # Performed in STIR by entering the att image as a normalization map

# Scatter Correction
analytic_scatt_corr_factor:  1      # 0.15 WILL REMOVE 85% of scatter.0 will remove scatter
stir_scatt_corr_smoothing:   1      # Will include smoothed SimSET scatter in the additive_sinogram.

# Randoms Correction
analytic_randoms_corr_factor: 1     # 0.15 WILL REMOVE 85% of scatter.0 will remove randoms
stir_randoms_corr_smoothing: 1      # Will include smoothed SimSET randoms in the additive_sinogram.

# Reconstruction
#--------------------------------------
recons_type: "OSEM3D"
max_segment: 39              # Maximum Ring difference on the reconstruction

# Configure Reconstruction output
zoomFactor: 1                # Zoom factor in x and y
xyOutputSize: 256
zOutputSize: 79  
xyOutputVoxelSize: 2         # mm
zOutputVoxelSize: 2          # mm
numberOfSubsets: 9           # Number of subsets
numberOfIterations: 10       # Number of iterations
savingInterval: 10           # The interval that we want to save intermediate subiterations images

# Filter
inter_iteration_filter: 0
subiteration_interval: 
x_dir_filter_FWHM:  # in mm
y_dir_filter_FWHM:  # in mm
z_dir_filter_FWHM:  # in mm