defaults:
 - scanner: discovery_st

simulation_environment: 0
sim_type: "SimSET"
do_simulation: 1
do_reconstruction: 1
divisions: 12
model_type: "cylindrical"
patient_dirname: "0"
act_map: "S1_actMap.nii"
att_map: "S1_attMap.nii"
output_dir: "0"
center_slice: 7
total_dose: 1
simulation_time: 30
sampling_photons: 2000000
photons: 15000000
add_randoms: 1
phglistmode: 0
detlistmode: 1
recons_type: 1
maximumIteration: 1
