defaults:
 - scanner: discovery_st

simulation_environment: 0
sim_type: "SimSET"
do_simulation: 1
do_reconstruction: 1
divisions: 12
model_type: "simple_pet"
patient_dirname: "test_image"
act_map: "act.hdr"
att_map: "att.hdr"
output_dir: "Test"
center_slice: 7
total_dose: 0.1
simulation_time: 30
sampling_photons: 2000000
photons: 15000000
add_randoms: 1
phglistmode: 0
detlistmode: 1
recons_type: 1
maximumIteration: 1
