numberOfSubsets: 14
numberOfIterations: 56
savingInterval: 28
analytical_att_correction: 1
stir_recons_att_corr: 0
analytic_scatt_corr_factor: 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D"
inter_iteration_filter: 0
subiteration_interval:
x_dir_filter_FWHM:
y_dir_filter_FWHM:
z_dir_filter_FWHM:
psf_value: 1.125
add_noise: 0.01
max_segment: 11
zoomFactor: 1.69
xyOutputSize: 128
zOutputSize: 35
zOutputVoxelSize: 4.25
