defaults:
  - params: randfig
only_log: false
log: true
job_type_wandb: "Toy database"
dir_stir: ${root_path:root}/include/STIR/install
dir_simset: ${root_path:root}/include/SimSET/2.9.2
matlab_mcr_path: ""
spm_path: ""
dir_data_path: ${root_path:root}/Subjects/Data
dir_results_path: ${mibiolab_home_path:root}/Data/Yere_simpet
interactive_mode: 0
stratification: "true"
forced_detection: "true"
forced_non_absortion: "true"
acceptance_angle: 90.0
positron_range: "true"
isotope: "f18"
non_colinearity: "true"
minimum_energy: 350.0
weight_window_ratio: 1.0
point_source_voxels: "false"
coherent_scatter_object: "false"
coherent_scatter_detector: "false"
