defaults:
  - params: randfig
dir_stir: /home/mibiolab/Work/yere/simpet/include/STIR/install
dir_simset: /home/mibiolab/Work/yere/simpet/include/SimSET/2.9.2
matlab_mcr_path: ""
spm_path: ""
dir_data_path: /home/mibiolab/Work/yere/simpet/Subjects/Data/
dir_results_path: /home/mibiolab/Work/yere/simpet/Subjects/Results/
interactive_mode: 0
stratification: "true"
forced_detection: "true"
forced_non_absortion: "true"
acceptance_angle: 90.0
positron_range: "true"
isotope: "f18"
non_colinearity: "true"
minimum_energy: 350.0
weight_window_ratio: 1.0
point_source_voxels: "false"
coherent_scatter_object: "false"
coherent_scatter_detector: "false"
