defaults:
        - scanner: Bruker_PET_MRI_scanner_Validado_modif_WE30 

simulation_environment: 1
sim_type: "SimSET"
do_simulation: 1       
do_reconstruction: 1 
divisions: 8
model_type: "cylindrical"                
patient_dirname: "Phantom_Rata_F98_GBM"
act_map: "Rat_F98_GBM_act_48h.hdr"                   
att_map: "Rat_Oficial_att.hdr"    
output_dir: "Rata_3_Zr89_48h_cama_2"
center_slice: 78   # cama 2            
total_dose:  0.1271
simulation_time: 600 #800      #600
sampling_photons: 20000000
photons: 0
add_randoms: 0 
phglistmode: 0
detlistmode: 0
recons_type: 0
maximumIteration: 1
