defaults:
 - scanner: NeuroLF_BPET_claudia_scanner_3mm_crystal_thickness

simulation_environment: 1
sim_type: "SimSET"
do_simulation: 0 
do_reconstruction: 1
divisions: 3 
model_type: "cylindrical"
patient_dirname: "NEMA_Resolution_Phantoms_NeuroLF"
act_map: "0_10_61_act.hdr"                #0_0_0_cyl+pto_act_60_54.hdr
att_map: "0_10_61_att.hdr"                    #prueba_cilindro_att.hdr
output_dir: "RS_3mm_0_10_61_fbp2d_REV_+time"   #3_Nueva_prueba_resolucion_180sec_1mCi
center_slice: 118              #pto_:118 
total_dose: 0.3     #nueva prueba 1.0               #0.3 resolucion espacial   
simulation_time: 80   #180   #40            
sampling_photons: 20000000      #200000
photons: 0
add_randoms: 0
phglistmode: 0
detlistmode: 0
recons_type: 0
maximumIteration: 1
