defaults:
 - scanner: NeuroLF_BPET_claudia_scanner

simulation_environment: 1
sim_type: "SimSET"
do_simulation: 1 
do_reconstruction: 1
divisions: 20 
model_type: "cylindrical"   #cylindrical
patient_dirname: "cylinder_uniformidad_260mm"
act_map: "act_260.nii"
att_map: "act_260.nii"
output_dir: "cilindro_260_6h"
center_slice: 400             #uniform_cyl:94 
total_dose: 0.8108            #0.8108 cylinder 
simulation_time: 21600          #21600 cylinder  
sampling_photons: 20000000      #200000
photons: 0
add_randoms: 0
phglistmode: 0
detlistmode: 0
recons_type: 0
maximumIteration: 1
