defaults:
 - scanner: Bruker_PET_MRI_scanner_Validado_modif_WE20

simulation_environment: 0
sim_type: "SimSET"
do_simulation: 1
do_reconstruction: 1
divisions: 5
model_type: "cylindrical"
patient_dirname: "Phantom_Phantech"
mask_dirname: "Phantom_Phantech/Reference"
act_map: "PET_study_1.hdr"
att_map: "RatPhantom_Phantech_att_aire.hdr"
mask_map: "Phantom_Phantech_Reference_mask.hdr"
output_dir: "PET_study_1_7.993uCi_att_aire"
center_slice: 7
total_dose: 0.00799
simulation_time: 600
sampling_photons: 2000000
photons: 0
add_randoms: 0
phglistmode: 0
detlistmode: 0
maximumIteration: 1

#Corrections:
correction_for_NECR: 1  # 0-NO 1-SI
correction_for_normalization: 1 # 0-No 1-Si 
correction_total_fov: 1   # 0-No 1-Si

#Quantification
quantification_info: 1 # 0-NO 1-SI

# Variables needed for whole body simulation
whole_body_simulation : 1 # 0-NO 1-SI
z_min: 0
z_max: 730
joints_beds: 1 # 0-NO 1-SI
