name: Build and run test simulations
on:
  pull_request:
  push:
jobs:
  build-and-run-test-simulations:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - run: make install
      - run: make dummy-data && python3.9 test.py
