name: Build and run test simulations
on:
  pull_request:
  push:
jobs:
  build-and-run-test-simulations:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - run: make install
      - run: make dummy-data
      - run: |
          apt-get update
          apt-get install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get -y -q install python3.9 python3.9-distutils python3-pip
          python3.9 -m pip install --upgrade pip
          pip3.9 install -r requirements.txt
